
server:
  port: 8766

spring:
  application:
    name: springcloud-user-reg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver    
    username: root
    password: root
    url: jdbc:mysql://192.168.1.132:3306/qsj?useUnicode=true&characterEncoding=utf-8&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




